### ISSUE TITLE
Add Psr\Log\LoggerInterface to classes to compile

### ISSUE THREAD

**Issue by gnugat** [symfony/MonologBundle#125]
Hello, since Monolog is based on PSR-3 most classes the depend on a logger can typehint against `Psr\Log\LoggerInterface`.
I was wondering if it could be added to the classes to compile ([here](https://github.com/symfony/MonologBundle/blob/master/DependencyInjection/MonologExtension.php#L88)), I haven't find any discussion about it so I'm not sure what are the arguments against it.

**Comment by stof** [comment]
A typehint does not require a class definition. Only implementation the interface does.

an btw, as ``Monolog\Logger`` is added to the compiled classes, the interface will be as well because of the way the compilation works (all parent classes and implemented interfaces are added too to avoid issues when loading the file)

**Comment by gnugat** [comment]
I see, thanks for the explanation :) .
